name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1 

    - name: Build, tag, and push image to ECR
      run: |
        REPOSITORY_URI=${{ secrets.AWS_REGION }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
        docker build -t myapp . 
        docker tag myapp:latest $REPOSITORY_URI:latest 
        docker push $REPOSITORY_URI:latest

    - name: Register Task Definition in ECS
      run: |
        TASK_DEFINITION=$(cat ecs-task-def.json | jq --arg IMAGE_URI "$REPOSITORY_URI:latest" '.containerDefinitions[0].image=$IMAGE_URI')
        echo "$TASK_DEFINITION" > myapp-task-def.json
        aws ecs register-task-definition --cli-input-json file://myapp-task-def.json

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --force-new-deployment
